image: pointsofinterest/gitlabr:latest

document:
  stage: document
  script:
  - R --vanilla -e 'library(devtools);  devtools::document(); devtools::document()'
  artifacts:
    paths:
    - man/
    - NAMESPACE

test:
  stage: test
  script:
  - R --vanilla -e 'library(devtools); library(testthat); devtools::test(reporter
    = StopReporter)'
  dependencies:
  - document

build:
  stage: build
  script:
  - R --vanilla -e 'library(devtools); devtools::build(path = "./")'
  artifacts:
    paths:
    - '*.tar.gz'
  dependencies:
  - document

check:
  stage: check
  script:
  - R --vanilla -e 'library(devtools);  tar_file <- file.path(getwd(), list.files(".",
    pattern = ".tar.gz")); results <- devtools::check_built(tar_file); stopifnot(sum(sapply(results,
    length)) <= 0)'
  dependencies:
  - build

push_to_github:
  stage: push
  only:
  - master
  script:
  - git push 'https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/jirkalewandowski/gitlabr.git'
    $(git symbolic-ref --short -q HEAD)

push_to_gitlab_com:
  stage: push
  only:
  - master
  script:
  - git push 'https://${GITLAB_COM_USERNAME}:${GITLAB_COM_PASSWORD}@gitlab.com/jirkalewandowski/gitlabr.git'
    $(git symbolic-ref --short -q HEAD)

stages:
- document
- test
- build
- check
- push

